#
# Module manifest for module 'HARpwn'
#
# Generated by: Christian Ritter
#
# Generated on: 4/10/2023
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'HARpwn.psm1'
    
    # Version number of this module.
    ModuleVersion = '0.1'
    
    # Supported PSEditions
    CompatiblePSEditions = 'Core'
    
    # ID used to uniquely identify this module
    GUID = 'a1b2c3d4-e5f6-7a8b-9c01-23d4e5f6a7b8'
    
    # Author of this module
    Author = 'Christian Ritter'
    
    # Company or vendor of this module
    CompanyName = ''
    
    # Copyright statement for this module
    Copyright = '(c) Christian Ritter. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'HARpwn: A PowerShell module for extracting and sanitizing HARTokens from HTTP Archive (HAR) files. Simplify token extraction and secure your HAR files with a touch of humor.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'
    
    # Functions to export from this module
    FunctionsToExport = @(
        'Get-HARToken',
        'Remove-HARToken'
    )
    
    # Cmdlets to export from this module
    CmdletsToExport = @()
    
    # Variables to export from this module
    VariablesToExport = @()
    
    # Aliases to export from this module
    AliasesToExport = @()
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('HARTokens', 'Security', 'Extraction')
    
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/HCRitter/HARpwn'
        }
    }
}
